use voleiSesi;
insert into pessoa (nome)
  values("ANDRÉ"),
  ("WELLINGTON"),
  ("BEATRIZ"),
  ("DANIEL"),
  ("DHARANA"),
  ("EDUARDA"),
  ("EDUARDO"),
  ("GABRIEL"),
  ("GABRIELLA"),
  ("GUILHERME"),
  ("GUSTAVO FREITAS"),
  ("GUSTAVO NAVES"),
  ("ISABELLA"),
  ("JOABE"),
  ("JOÃO CARLOS"),
  ("JOÃO HELIO"),
  ("JOÃO VICTOR"),
  ("KAIQUE"),
  ("LORENA"),
  ("LUCAS"),
  ("LUIZA"),
  ("MARIA CLARA CORRÊA"),
  ("MARIA CLARA MACHADO"),
  ("MARIA EDUARDA DE BARROS"),
  ("MARIA EDUARDA SANTONI"),
  ("MARIA JULIA"),
  ("MARYANA"),
  ("NEWTON"),
  ("OTAVIO"),
  ("PAULO"),
  ("PEDRO"),
  ("SOPHIA"),
  ("THARYNE"),
  ("YAGO");